### ISSUE TITLE
进行二次开发

### ISSUE THREAD

**Issue by dmucby** [QT-learn-lib/P4-and-ONOS-development#1]
我们团队纠结于P4与ONOS的连接问题很久，直到看到你们的项目，并在项目上进行了一些实验，但是由于某些环境的问题，仍存在问题。
  我们计划在该项目进行二次开发，请问能否将你们的环境通过邮箱发给我们，如果可以，我们将十分感谢！这是邮箱地址：cby@dlmu.edu.cn

**Comment by QT-learn-lib** [comment]
你好，我是用服务器做的仿真，不是用虚拟机做的。你可以根据实验给出的运行环境进行搭建。

**Comment by dmucby** [comment]
你好，谢谢你的回答。由于本机安装ONOS比较复杂，而且我尝试后发现由于网络相关问题一直不能成功。因此使用docker来创建ONOS容器，而我在重复你的实验时，发现启动拓扑一直失误，我一开始是认为是ONOS服务IP地址的问题，由于脚本文件bmv2.py没有说明，我不知道去更改，希望你能给你的建议，谢谢！

**Comment by dmucby** [comment]
bmv2-s1-log 报错如图：
![image](https://user-images.githubusercontent.com/80476712/167967558-f421ff99-a9b1-4807-ade1-dc49910fb55a.png)

**Comment by dmucby** [comment]
现在我已经完成了拓扑的构建，并发现了交换机，但是我们现在要开发一个应用，让这个应用能下发我在P4中自定义的table和action的流表，我可以手动填充相关信息，请问有相关的ONOS的API吗？或者有关的介绍文章或者示例代码对我的帮助也是十分巨大，十分感谢！

**Comment by QT-learn-lib** [comment]
ONOS与P4实验：https://github.com/opennetworkinglab/ngsdn-tutorial
ONOS API: http://api.onosproject.org/2.3.0/apidocs/




邱涛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QT-learn-lib/P4-and-ONOS-development"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 上午8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QT-learn-lib/P4-and-ONOS-development] 进行二次开发 (Issue #1)





 
现在我已经完成了拓扑的构建，并发现了交换机，但是我们现在要开发一个应用，让这个应用能下发我在P4中自定义的table和action的流表，我可以手动填充相关信息，请问有相关的ONOS的API吗？或者有关的介绍文章或者示例代码对我的帮助也是十分巨大，十分感谢！

**Comment by dmucby** [comment]
谢谢你的链接！

**Comment by dmucby** [comment]
还有个需要帮助的地方，能问下有相关你存储库中bmv2.py的文档吗？我准备进行相关改写工作。谢谢

**Comment by QT-learn-lib** [comment]
抱歉，没有相关文档
